### ISSUE TITLE
Interface library causes build failure on Humble/20.04

### ISSUE THREAD

**Issue by Ayush1285** [ros/filters#75] opened 2024-03-29 17:20 UTC
I am trying to build this using `colcon build` command. But it is not working, following error shows up:
`--- stderr: filters                         
CMake Error at CMakeLists.txt:26 (add_library):
  add_library INTERFACE library requires no source arguments.

CMake Error at CMakeLists.txt:31 (target_link_libraries):
  Cannot specify link libraries for target "realtime_circular_buffer" which
  is not built by this project.

---
Failed   <<< filters [6.26s, exited with code 1]`

It says INTERFACE library requires no source arguments. how can I resolve this without specifying the source files?

**Comment by jonbinney** [comment] 2024-03-29 17:24
What branch are you on? What ROS distro? What OS version?

**Comment by Ayush1285** [comment] 2024-03-29 17:32
My bad for not mentioning all the details.
Branch - ros2
ROS Distro - humble (source installation)
OS version - Ubuntu 20.04

**Comment by jonbinney** [comment] 2024-03-29 17:36
Let me try to reproduce this - I've got a similar setup

**Comment by jonbinney** [comment] 2024-03-29 17:43
This doesn't happen on 22.04 on humble; I'm guessing a recent commit added something that doesn't work with the older cmake version. Could you try a previous commit of filters using `git checkout 7b1b525c3529c00cdbe7edcb36cc53b56781df2d` and let me know if that builds?  Also, what is the output of `cmake --version`?

**Comment by Ayush1285** [comment] 2024-03-29 17:57
Yes, it builds for the previous commit. My cmake version is 3.16.3. In the CMakeLists.txt for the ros2 branch, minimum cmake version required was 3.14, so I thought it should be okay.

**Comment by jonbinney** [comment] 2024-03-29 18:07
It looks like interface libraries with sources was added in 3.19. CI for humble runs on 22.04, so I missed this problem. The interface library was added in https://github.com/ros/filters/pull/70

@wep21 @ryanf55 it looks like the interface library for realtime_circular buffer doesn't work with the cmake version on 20.04, which is a supported platform for humble. Thoughts? I could branch for humble, rollback the interface library changes, and re-release, but is there a way to support the older cmake version instead?

**Comment by jonbinney** [comment] 2024-03-29 18:20
Ubuntu 20.04 is only "recommended" to support for humble packages, but since filters is pretty core I think we should support it. Here are the cmake versions for each platform of humble:

![image](https://github.com/ros/filters/assets/1538056/f1dbd20e-c913-4ad1-83fc-e1314257504d)

Since interface libraries with source arguments was only added in cmake 3.19, it would seem to break support for macos and bullseye as well.

**Comment by Ayush1285** [comment] 2024-03-29 19:38
Thanks for the help!!
I'll use the previous version.

**Comment by Ryanf55** [comment] 2024-03-29 22:44
> Ubuntu 20.04 is only "recommended" to support for humble packages, but since filters is pretty core I think we should support it. Here are the cmake versions for each platform of humble:
> 
> ![image](https://private-user-images.githubusercontent.com/1538056/318113311-f1dbd20e-c913-4ad1-83fc-e1314257504d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTI0ODMsIm5iZiI6MTcxMTc1MjE4MywicGF0aCI6Ii8xNTM4MDU2LzMxODExMzMxMS1mMWRiZDIwZS1jOTEzLTRhZDEtODNmYy1lMTMxNDI1NzUwNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMjI0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I5ZTZhNjAzM2U0ZmU3NzEyYmI0ZTAwZGJmYmE4NTcyNGFkMjQ0NDg0NzA5YjE2ODEzZDA2ZmRmZDdiMmIzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SNYH-PPIkU4fvR_2FRktEwiVk6MNJacYPfpuyV3uikY)
> 
> Since interface libraries with source arguments was only added in cmake 3.19, it would seem to break support for macos and bullseye as well.

Only bullseye, true. MacOS is rolling release - it's currently 3.29. The version in REP-2000 is just what it had when they wrote the REP.
https://formulae.brew.sh/formula/cmake


Edit: To answer your other question - yes. I'll get a PR up next week for you to fix debian bullseye. It will require conditional logic. Anyone compiling with CMake 3.19 or greater will get the header files to show up properly in their editors. 3.18 won't, but the library can still be linked to. 
https://stackoverflow.com/questions/60604249/how-to-make-a-header-only-library-with-cmake

**Comment by Ryanf55** [comment] 2024-04-01 02:44
Proposed patch:
https://github.com/ros/filters/pull/76

**Comment by jonbinney** [comment] 2024-08-18 22:22
I believe this was fixed by #76 .

**Closed as completed by jonbinney** 2024-08-18 22:22 UTC
